# 실행할 개별 컨테이너 정의
services:
  # MySQL 데이터베이스 컨테이너
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - 3309:3306
    volumes:
      - mysql_data:/var/lib/mysql

  # FastAPI 백엔드 서버 컨테이너
  api:
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./api:/app
    ports:
      - "9000:8000"
    depends_on:
      - db

  # adminer 데이터베이스 관리 도구 컨테이너
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

# MySQL 데이터를 로컬에 영구 저장
volumes:
  mysql_data: