name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Docker
      run: |
        sudo systemctl start docker
        sudo systemctl enable docker
        
    - name: Create environment file
      run: |
        cd ${{ github.workspace }}
        cat > .env << EOF
        DB_USER=${{ secrets.DB_USER }}
        DB_PASSWORD=${{ secrets.DB_PASSWORD }}
        DB_HOST=${{ secrets.DB_HOST }}
        DB_PORT=${{ secrets.DB_PORT }}
        DB_NAME=${{ secrets.DB_NAME }}
        JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}
        EOF
        
    - name: Deploy with Docker Compose
      run: |
        cd ${{ github.workspace }}
        docker-compose down
        docker-compose build --no-cache
        docker-compose up -d
        
    - name: Verify deployment
      run: |
        sleep 10
        curl -f http://localhost:9000/health/ || exit 1
        
    - name: Show logs
      run: |
        docker-compose logs --tail=50
