name: Deploy to Azure VM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to Azure VM
      run: |
        ssh azureuser@${{ secrets.VM_HOST }} << 'EOF'
          cd /home/azureuser/dermacare-engine
          git pull origin main
          
          # Docker 서비스 재시작
          # 1. 모든 컨테이너와 네트워크 정리
          docker-compose down --remove-orphans

          # 2. 새로 빌드하고 시작
          docker-compose build --no-cache
          docker-compose up -d
        EOF
        
    - name: Verify deployment
      run: |
        sleep 2
        curl -f http://${{ secrets.VM_HOST }}:9000/health/ || exit 1
        
    - name: Show logs
      run: |
        ssh azureuser@${{ secrets.VM_HOST }} "cd /home/azureuser/dermacare-engine && docker-compose logs --tail=50"
